# Generated by Django 4.1.4 on 2023-01-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
